"""
modules/delivery.py
-------------------
Digest delivery: email (SMTP) and WhatsApp (Twilio/wa.me link).
"""
from __future__ import annotations
import os
import smtplib
import urllib.parse
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# ── Email ─────────────────────────────────────────────────────────────────────

def send_email_digest(
    to_addr: str,
    subject: str,
    body_text: str,
    body_html: str = "",
    smtp_host: str = "",
    smtp_port: int = 587,
    smtp_user: str = "",
    smtp_pass: str = "",
) -> tuple[bool, str]:
    """Send the daily digest via SMTP."""
    host = smtp_host or os.environ.get("SMTP_HOST", "smtp.gmail.com")
    port = smtp_port or int(os.environ.get("SMTP_PORT", 587))
    user = smtp_user or os.environ.get("SMTP_USER", "")
    pwd = smtp_pass or os.environ.get("SMTP_PASS", "")

    if not user or not pwd:
        return False, "SMTP credentials not configured."

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = user
        msg["To"] = to_addr

        msg.attach(MIMEText(body_text, "plain"))
        if body_html:
            msg.attach(MIMEText(body_html, "html"))

        with smtplib.SMTP(host, port) as server:
            server.ehlo()
            server.starttls()
            server.login(user, pwd)
            server.sendmail(user, to_addr, msg.as_string())
        return True, "Email sent successfully!"
    except Exception as e:
        return False, str(e)


def build_html_digest(digest: dict, articles: list[dict]) -> str:
    """Build a rich HTML email for the digest."""
    sections_html = ""
    for section in digest.get("sections", []):
        stories_html = "".join([
            f'<li><strong>{s.get("title","")}</strong>: {s.get("insight","")}</li>'
            for s in section.get("stories", [])
        ])
        sections_html += f"""
        <div style="margin-bottom:24px;">
            <h3 style="color:#10B981;border-bottom:1px solid #10B98133;padding-bottom:6px;">
                {section.get("category","")}
            </h3>
            <p style="font-weight:bold;color:#E2E8F0;">{section.get("headline","")}</p>
            <ul style="color:#CBD5E1;">{stories_html}</ul>
            <p style="background:#1E3A2A;padding:10px;border-radius:6px;color:#6EE7B7;">
                💡 {section.get("takeaway","")}
            </p>
        </div>"""

    themes = "".join([f'<span style="background:#1E3A2A;color:#6EE7B7;padding:4px 10px;border-radius:12px;margin:3px;display:inline-block;">{t}</span>'
                      for t in digest.get("key_themes", [])])

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><style>
body {{ font-family: -apple-system, sans-serif; background: #080B14; color: #E2E8F0; margin:0; padding:0; }}
.container {{ max-width: 680px; margin: 0 auto; padding: 32px 24px; }}
.header {{ background: linear-gradient(135deg, #0F1521, #1A2A1A); border-radius: 16px;
           padding: 24px; margin-bottom: 24px; border: 1px solid #10B98133; }}
h1 {{ color: #10B981; font-size: 1.4rem; margin: 0 0 8px; }}
.overview {{ background: #0F1521; border-left: 3px solid #10B981; padding: 14px 18px;
             border-radius: 0 8px 8px 0; color: #CBD5E1; line-height: 1.6; margin-bottom: 20px; }}
.footer {{ text-align: center; color: #374151; font-size: 0.8rem; margin-top: 32px; }}
</style></head>
<body><div class="container">
<div class="header">
    <h1>📰 {digest.get("title", "Daily News Brief")}</h1>
    <div style="color:#6B7280;font-size:0.85rem;">Sentiment: {digest.get("sentiment_overview","")} · Word of the day: <em>{digest.get("word_of_day","")}</em></div>
</div>
<div class="overview">{digest.get("overview","")}</div>
<div style="margin-bottom:16px;">{themes}</div>
{sections_html}
<div class="footer">Generated by AI News Agent · Unsubscribe</div>
</div></body></html>"""


# ── WhatsApp ──────────────────────────────────────────────────────────────────

def build_whatsapp_message(digest: dict, articles: list[dict]) -> str:
    """Build a compact WhatsApp-friendly message (< 1000 chars)."""
    date = digest.get("title", "Daily Brief").replace("Morning Intelligence Brief — ", "")
    overview = digest.get("overview", "")[:300]
    themes = " · ".join(digest.get("key_themes", [])[:3])

    top_stories = sorted(articles, key=lambda x: x.get("signal_score", 0), reverse=True)[:3]
    stories_text = "\n".join([
        f"• {a['title'][:70]}" for a in top_stories
    ])

    return f"""📰 *AI News Brief — {date}*

{overview}

*Top Themes:* {themes}

*Top Stories:*
{stories_text}

_Powered by AI News Agent_"""


def get_whatsapp_link(phone: str, message: str) -> str:
    """Generate a wa.me share link."""
    encoded = urllib.parse.quote(message)
    clean_phone = phone.replace("+", "").replace(" ", "").replace("-", "")
    return f"https://wa.me/{clean_phone}?text={encoded}"


# ── Demo send (logs to console) ───────────────────────────────────────────────

def demo_send(method: str, target: str, message: str) -> tuple[bool, str]:
    """Simulate delivery (for demo/testing without real credentials)."""
    print(f"[DEMO {method.upper()}] To: {target}\n{message[:200]}...")
    return True, f"Demo {method} delivery logged to console."
