"""
exporter.py — Export meeting notes to PDF, DOCX, and Markdown.
"""

import io
from datetime import datetime


def _format_date() -> str:
    return datetime.now().strftime("%B %d, %Y")


# ─────────────────────────────────────────────
# Markdown Export
# ─────────────────────────────────────────────

def export_markdown(analysis: dict, transcript: str, follow_up_email: str) -> str:
    """Generate a comprehensive Markdown report."""
    title = analysis.get("title", "Meeting Notes")
    date = analysis.get("date_mentioned", _format_date())
    attendees = analysis.get("attendees", [])
    summary = analysis.get("summary", "")
    decisions = analysis.get("decisions", [])
    action_items = analysis.get("action_items", [])
    tasks_by_person = analysis.get("tasks_by_person", {})
    key_topics = analysis.get("key_topics", [])
    risks = analysis.get("risks_blockers", [])
    follow_ups = analysis.get("follow_up_questions", [])
    sentiment = analysis.get("sentiment", "")
    effectiveness = analysis.get("meeting_effectiveness", "")
    next_meeting = analysis.get("next_meeting_suggested", "")

    md = f"""# {title}

**Date:** {date}  
**Attendees:** {", ".join(attendees) if attendees else "Not specified"}  
**Sentiment:** {sentiment}  
**Meeting Effectiveness:** {effectiveness}  
{"**Next Meeting:** " + next_meeting if next_meeting else ""}

---

## Executive Summary

{summary}

---

## Key Topics Discussed

{chr(10).join(f"- {t}" for t in key_topics) if key_topics else "- Not extracted"}

---

## Decisions Made

{chr(10).join(f"### {i+1}. {d['decision']}{chr(10)}**Owner:** {d.get('owner','TBD')}  {chr(10)}**Context:** {d.get('context','')}{chr(10)}" for i, d in enumerate(decisions)) if decisions else "No decisions recorded."}

---

## Action Items

| # | Task | Owner | Deadline | Priority |
|---|------|-------|----------|----------|
{chr(10).join(f"| {i+1} | {ai['task']} | {ai.get('owner','TBD')} | {ai.get('deadline','TBD')} | {ai.get('priority','Medium')} |" for i, ai in enumerate(action_items)) if action_items else "| - | No action items recorded | - | - | - |"}

---

## Tasks by Person

{chr(10).join(f"### {person}{chr(10)}{chr(10).join(f'- {task}' for task in tasks)}{chr(10)}" for person, tasks in tasks_by_person.items()) if tasks_by_person else "Not extracted."}

---

## Risks & Blockers

{chr(10).join(f"- ⚠️ {r}" for r in risks) if risks else "None identified."}

---

## Follow-up Questions

{chr(10).join(f"- ❓ {q}" for q in follow_ups) if follow_ups else "None recorded."}

---

## Follow-up Email Draft

```
{follow_up_email}
```

---

## Full Transcript

{transcript}

---
*Generated by AI Meeting Notes Agent on {_format_date()}*
"""
    return md


# ─────────────────────────────────────────────
# PDF Export
# ─────────────────────────────────────────────

def export_pdf(analysis: dict, transcript: str, follow_up_email: str) -> bytes:
    """Generate a professional PDF report using ReportLab."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            HRFlowable, Paragraph, SimpleDocTemplate,
            Spacer, Table, TableStyle, PageBreak,
        )

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer, pagesize=letter,
            rightMargin=0.75*inch, leftMargin=0.75*inch,
            topMargin=0.75*inch, bottomMargin=0.75*inch,
        )
        styles = getSampleStyleSheet()

        # Custom styles
        INDIGO = colors.HexColor("#4f46e5")
        DARK = colors.HexColor("#0f172a")
        GRAY = colors.HexColor("#64748b")
        LIGHT_BG = colors.HexColor("#f8fafc")
        GREEN = colors.HexColor("#16a34a")
        RED = colors.HexColor("#dc2626")
        AMBER = colors.HexColor("#d97706")

        def style(name, **kwargs):
            base = styles["Normal"]
            return ParagraphStyle(name, parent=base, **kwargs)

        title_s = style("TitleS", fontSize=22, fontName="Helvetica-Bold",
                        textColor=DARK, spaceAfter=4, leading=26)
        h1_s = style("H1S", fontSize=14, fontName="Helvetica-Bold",
                     textColor=INDIGO, spaceAfter=6, spaceBefore=14, leading=18)
        h2_s = style("H2S", fontSize=12, fontName="Helvetica-Bold",
                     textColor=DARK, spaceAfter=4, spaceBefore=10, leading=15)
        body_s = style("BodyS", fontSize=10, leading=15, spaceAfter=4, textColor=DARK)
        meta_s = style("MetaS", fontSize=10, textColor=GRAY, spaceAfter=2)
        bullet_s = style("BulletS", fontSize=10, leading=14, leftIndent=16,
                         spaceAfter=3, textColor=DARK)
        code_s = style("CodeS", fontSize=9, fontName="Courier", leading=13,
                       textColor=colors.HexColor("#374151"), spaceAfter=3)

        story = []

        # ── Header ──
        story.append(Paragraph(analysis.get("title", "Meeting Notes"), title_s))
        date = analysis.get("date_mentioned", _format_date())
        attendees = ", ".join(analysis.get("attendees", ["Not specified"]))
        story.append(Paragraph(f"Date: {date}", meta_s))
        story.append(Paragraph(f"Attendees: {attendees}", meta_s))
        sent = analysis.get("sentiment", "")
        eff = analysis.get("meeting_effectiveness", "")
        story.append(Paragraph(f"Sentiment: {sent}  |  Effectiveness: {eff}", meta_s))
        story.append(HRFlowable(width="100%", thickness=2, color=INDIGO))
        story.append(Spacer(1, 0.1*inch))

        # ── Summary ──
        story.append(Paragraph("Executive Summary", h1_s))
        story.append(Paragraph(analysis.get("summary", "").replace("&", "&amp;").replace("<", "&lt;"), body_s))

        # ── Key Topics ──
        topics = analysis.get("key_topics", [])
        if topics:
            story.append(Paragraph("Key Topics", h1_s))
            for t in topics:
                story.append(Paragraph(f"• {t}", bullet_s))

        # ── Decisions ──
        decisions = analysis.get("decisions", [])
        if decisions:
            story.append(Paragraph("Decisions Made", h1_s))
            for i, d in enumerate(decisions, 1):
                story.append(Paragraph(f"{i}. {d['decision']}", h2_s))
                story.append(Paragraph(f"Owner: {d.get('owner','TBD')}  |  {d.get('context','')}", meta_s))

        # ── Action Items Table ──
        action_items = analysis.get("action_items", [])
        if action_items:
            story.append(Paragraph("Action Items", h1_s))
            table_data = [["#", "Task", "Owner", "Deadline", "Priority"]]
            priority_colors = {"High": RED, "Medium": AMBER, "Low": GREEN}
            for i, ai in enumerate(action_items, 1):
                table_data.append([
                    str(i),
                    ai.get("task", "")[:60],
                    ai.get("owner", "TBD"),
                    ai.get("deadline", "TBD"),
                    ai.get("priority", "Medium"),
                ])
            t = Table(table_data, colWidths=[0.3*inch, 3.2*inch, 1.2*inch, 1.1*inch, 0.8*inch])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0,0), (-1,0), INDIGO),
                ("TEXTCOLOR", (0,0), (-1,0), colors.white),
                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
                ("FONTSIZE", (0,0), (-1,-1), 9),
                ("ROWBACKGROUNDS", (0,1), (-1,-1), [LIGHT_BG, colors.white]),
                ("GRID", (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
                ("TOPPADDING", (0,0), (-1,-1), 5),
                ("BOTTOMPADDING", (0,0), (-1,-1), 5),
                ("LEFTPADDING", (0,0), (-1,-1), 6),
                ("ALIGN", (0,0), (0,-1), "CENTER"),
                ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
            ]))
            story.append(t)
            story.append(Spacer(1, 0.1*inch))

        # ── Tasks by Person ──
        tasks_by_person = analysis.get("tasks_by_person", {})
        if tasks_by_person:
            story.append(Paragraph("Tasks by Person", h1_s))
            for person, tasks in tasks_by_person.items():
                story.append(Paragraph(person, h2_s))
                for task in tasks:
                    story.append(Paragraph(f"• {task}", bullet_s))

        # ── Risks ──
        risks = analysis.get("risks_blockers", [])
        if risks:
            story.append(Paragraph("Risks & Blockers", h1_s))
            for r in risks:
                story.append(Paragraph(f"⚠ {r}", bullet_s))

        # ── Follow-up Email ──
        if follow_up_email:
            story.append(PageBreak())
            story.append(Paragraph("Follow-up Email Draft", h1_s))
            story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
            story.append(Spacer(1, 0.05*inch))
            for line in follow_up_email.split("\n"):
                safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe or " ", code_s))

        # ── Transcript ──
        story.append(PageBreak())
        story.append(Paragraph("Full Transcript", h1_s))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
        story.append(Spacer(1, 0.05*inch))
        # Chunk transcript into paragraphs for PDF
        for chunk in transcript.split("\n"):
            chunk = chunk.strip()
            if chunk:
                safe = chunk.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe, code_s))

        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(f"Generated by AI Meeting Notes Agent · {_format_date()}", meta_s))

        doc.build(story)
        buffer.seek(0)
        return buffer.read()

    except ImportError:
        return b"reportlab not installed. Run: pip install reportlab"
    except Exception as e:
        return f"PDF generation error: {e}".encode()


# ─────────────────────────────────────────────
# DOCX Export
# ─────────────────────────────────────────────

def export_docx(analysis: dict, transcript: str, follow_up_email: str) -> bytes:
    """Generate a Word document using python-docx."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()

        # Page margins
        for section in doc.sections:
            section.top_margin = Inches(0.75)
            section.bottom_margin = Inches(0.75)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)

        INDIGO = RGBColor(0x4f, 0x46, 0xe5)
        DARK = RGBColor(0x0f, 0x17, 0x2a)
        GRAY = RGBColor(0x64, 0x74, 0x8b)

        def add_heading(text, level=1, color=None):
            p = doc.add_heading(text, level=level)
            if color:
                for run in p.runs:
                    run.font.color.rgb = color
            return p

        def add_para(text, bold=False, color=None, size=10):
            p = doc.add_paragraph()
            run = p.add_run(text)
            run.bold = bold
            run.font.size = Pt(size)
            if color:
                run.font.color.rgb = color
            return p

        def add_bullet(text, color=None):
            p = doc.add_paragraph(text, style="List Bullet")
            if color:
                for run in p.runs:
                    run.font.color.rgb = color
            return p

        # Title
        title_para = doc.add_heading(analysis.get("title", "Meeting Notes"), 0)
        for run in title_para.runs:
            run.font.color.rgb = DARK
            run.font.size = Pt(20)

        add_para(f"Date: {analysis.get('date_mentioned', _format_date())}", color=GRAY)
        add_para(f"Attendees: {', '.join(analysis.get('attendees', ['Not specified']))}", color=GRAY)
        add_para(f"Sentiment: {analysis.get('sentiment', '')}  |  Effectiveness: {analysis.get('meeting_effectiveness', '')}", color=GRAY)
        doc.add_paragraph("─" * 60)

        # Summary
        add_heading("Executive Summary", 1, INDIGO)
        doc.add_paragraph(analysis.get("summary", ""))

        # Key Topics
        topics = analysis.get("key_topics", [])
        if topics:
            add_heading("Key Topics", 1, INDIGO)
            for t in topics:
                add_bullet(t)

        # Decisions
        decisions = analysis.get("decisions", [])
        if decisions:
            add_heading("Decisions Made", 1, INDIGO)
            for i, d in enumerate(decisions, 1):
                add_para(f"{i}. {d['decision']}", bold=True)
                add_para(f"   Owner: {d.get('owner','TBD')} | {d.get('context','')}", color=GRAY)

        # Action Items
        action_items = analysis.get("action_items", [])
        if action_items:
            add_heading("Action Items", 1, INDIGO)
            table = doc.add_table(rows=1, cols=5)
            table.style = "Table Grid"
            hdr = table.rows[0].cells
            for i, h in enumerate(["#", "Task", "Owner", "Deadline", "Priority"]):
                hdr[i].text = h
                for para in hdr[i].paragraphs:
                    for run in para.runs:
                        run.bold = True
            for i, ai in enumerate(action_items, 1):
                row = table.add_row().cells
                row[0].text = str(i)
                row[1].text = ai.get("task", "")
                row[2].text = ai.get("owner", "TBD")
                row[3].text = ai.get("deadline", "TBD")
                row[4].text = ai.get("priority", "Medium")

        # Tasks by Person
        tasks_by_person = analysis.get("tasks_by_person", {})
        if tasks_by_person:
            add_heading("Tasks by Person", 1, INDIGO)
            for person, tasks in tasks_by_person.items():
                add_para(person, bold=True)
                for task in tasks:
                    add_bullet(f"  {task}")

        # Risks
        risks = analysis.get("risks_blockers", [])
        if risks:
            add_heading("Risks & Blockers", 1, INDIGO)
            for r in risks:
                add_bullet(f"⚠ {r}")

        # Follow-up Email
        if follow_up_email:
            doc.add_page_break()
            add_heading("Follow-up Email Draft", 1, INDIGO)
            for line in follow_up_email.split("\n"):
                p = doc.add_paragraph(line or " ")
                p.runs[0].font.size = Pt(10) if p.runs else None

        # Transcript
        doc.add_page_break()
        add_heading("Full Transcript", 1, INDIGO)
        p = doc.add_paragraph(transcript)
        p.runs[0].font.size = Pt(9)

        add_para(f"Generated by AI Meeting Notes Agent · {_format_date()}", color=GRAY)

        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        return buf.read()

    except ImportError:
        return b"python-docx not installed. Run: pip install python-docx"
    except Exception as e:
        return f"DOCX generation error: {e}".encode()
