"""
exporter.py — Export SEO audit reports to PDF and Markdown.
"""

import io
from datetime import datetime


def _date() -> str:
    return datetime.now().strftime("%B %d, %Y")


# ── Markdown Export ───────────────────────────────────────────────────────────

def export_markdown(raw: dict, audit: dict, ai: dict) -> str:
    url   = raw.get("url","")
    score = audit.get("overall_score",0)
    label, _ = _score_label(score)
    dt    = _date()

    lines = [
        f"# SEO Audit Report — {url}",
        f"**Date:** {dt}  |  **Score:** {score}/100 ({label})\n",
        "---",
        "## Executive Summary",
        ai.get("improvements",{}).get("executive_summary","Not available."),
        "",
        "## Top 3 Priorities",
    ]
    for p in ai.get("improvements",{}).get("top_3_priorities",[]):
        lines.append(f"1. {p}")

    # Category scores
    lines += ["","## Category Scores","","| Category | Score |","|---------:|------:|"]
    for cat in ["meta","headings","keywords","technical","images","links"]:
        s = audit.get(cat,{}).get("score",0)
        lines.append(f"| {cat.title()} | {s}/100 |")

    # Issues by severity
    lines += ["","## Critical Issues"]
    found = False
    for cat_name, cat_data in audit.items():
        if not isinstance(cat_data, dict): continue
        for iss in cat_data.get("issues",[]):
            if iss.get("severity") == "critical":
                lines.append(f"- ❌ **{cat_name.title()}**: {iss['message']}")
                if iss.get("fix"):
                    lines.append(f"  - *Fix:* {iss['fix']}")
                found = True
    if not found:
        lines.append("No critical issues found! 🎉")

    lines += ["","## Warnings"]
    for cat_name, cat_data in audit.items():
        if not isinstance(cat_data, dict): continue
        for iss in cat_data.get("issues",[]):
            if iss.get("severity") == "warning":
                lines.append(f"- ⚠️ **{cat_name.title()}**: {iss['message']}")

    # AI Suggestions
    impr = ai.get("improvements",{})
    if impr.get("quick_wins"):
        lines += ["","## Quick Wins (Fix Now)"]
        for qw in impr.get("quick_wins",[]):
            lines.append(f"- **{qw.get('action','')}** [{qw.get('impact','')} impact]")
            if qw.get("detail"):
                lines.append(f"  - {qw['detail']}")

    content = ai.get("content",{})
    if content.get("title_options"):
        lines += ["","## Recommended Title Options"]
        for t in content.get("title_options",[]):
            lines.append(f"- {t} ({len(t)} chars)")

    if content.get("description_options"):
        lines += ["","## Recommended Meta Descriptions"]
        for d in content.get("description_options",[]):
            lines.append(f"- {d} ({len(d)} chars)")

    kw_strat = ai.get("keywords",{})
    if kw_strat.get("long_tail_opportunities"):
        lines += ["","## Keyword Opportunities"]
        for kw in kw_strat.get("long_tail_opportunities",[]):
            lines.append(f"- {kw}")

    ux = ai.get("ux",{})
    if ux.get("readability_tips"):
        lines += ["","## UX Improvements"]
        for tip in ux.get("readability_tips",[]):
            lines.append(f"- {tip}")

    lines += ["","---",
              f"*Generated by AI SEO Audit Agent · [adityasharma.ai](https://www.adityasharma.ai) · {dt}*"]

    return "\n".join(lines)


def _score_label(score: int) -> tuple:
    if score >= 85: return "Excellent","#22c55e"
    if score >= 70: return "Good","#84cc16"
    if score >= 50: return "Needs Work","#f59e0b"
    return "Poor","#ef4444"


# ── PDF Export ────────────────────────────────────────────────────────────────

def export_pdf(raw: dict, audit: dict, ai: dict) -> bytes:
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.lib.units import inch
        from reportlab.platypus import (
            HRFlowable, PageBreak, Paragraph, SimpleDocTemplate,
            Spacer, Table, TableStyle,
        )

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter,
                                rightMargin=0.75*inch, leftMargin=0.75*inch,
                                topMargin=0.75*inch, bottomMargin=0.75*inch)
        styles = getSampleStyleSheet()

        # Colors
        INDIGO = colors.HexColor("#4f46e5"); DARK = colors.HexColor("#0f172a")
        GRAY   = colors.HexColor("#64748b"); GREEN = colors.HexColor("#22c55e")
        RED    = colors.HexColor("#ef4444"); AMBER = colors.HexColor("#f59e0b")
        LIGHT  = colors.HexColor("#f8fafc")

        def sty(name, **kw):
            return ParagraphStyle(name, parent=styles["Normal"], **kw)

        h1 = sty("H1", fontSize=20, fontName="Helvetica-Bold", textColor=DARK, spaceAfter=4, leading=24)
        h2 = sty("H2", fontSize=14, fontName="Helvetica-Bold", textColor=INDIGO, spaceAfter=6, spaceBefore=14, leading=18)
        h3 = sty("H3", fontSize=11, fontName="Helvetica-Bold", textColor=DARK, spaceAfter=4, spaceBefore=8, leading=14)
        body = sty("Body", fontSize=10, leading=15, spaceAfter=4, textColor=DARK)
        meta = sty("Meta", fontSize=10, textColor=GRAY, spaceAfter=2)
        bullet = sty("Bullet", fontSize=10, leftIndent=14, spaceAfter=3, leading=14, textColor=DARK)

        story = []
        url   = raw.get("url","")
        score = audit.get("overall_score",0)
        label, _ = _score_label(score)

        # Header
        story.append(Paragraph(f"SEO Audit Report", h1))
        story.append(Paragraph(url, meta))
        story.append(Paragraph(f"Score: {score}/100 — {label}  |  Date: {_date()}", meta))
        story.append(HRFlowable(width="100%", thickness=2, color=INDIGO))
        story.append(Spacer(1, 0.1*inch))

        # Executive summary
        summ = ai.get("improvements",{}).get("executive_summary","")
        if summ:
            story.append(Paragraph("Executive Summary", h2))
            story.append(Paragraph(summ.replace("&","&amp;").replace("<","&lt;"), body))

        # Score table
        story.append(Paragraph("Category Scores", h2))
        cats = [("Meta Tags","meta"),("Headings","headings"),("Keywords","keywords"),
                ("Technical","technical"),("Images","images"),("Links","links")]
        tdata = [["Category","Score","Status"]]
        for lbl, key in cats:
            s = audit.get(key,{}).get("score",0)
            status = "✓ Good" if s >= 70 else ("! Warning" if s >= 50 else "✗ Poor")
            sc = GREEN if s >= 70 else (AMBER if s >= 50 else RED)
            tdata.append([lbl, f"{s}/100", status])
        t = Table(tdata, colWidths=[3*inch, 1.2*inch, 1.5*inch])
        t.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),INDIGO), ("TEXTCOLOR",(0,0),(-1,0),colors.white),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"), ("FONTSIZE",(0,0),(-1,-1),10),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[LIGHT,colors.white]),
            ("GRID",(0,0),(-1,-1),0.5,colors.HexColor("#e2e8f0")),
            ("TOPPADDING",(0,0),(-1,-1),6), ("BOTTOMPADDING",(0,0),(-1,-1),6),
        ]))
        story.append(t); story.append(Spacer(1,0.1*inch))

        # Critical issues
        story.append(Paragraph("Critical Issues", h2))
        crits = [i for cat in audit.values() if isinstance(cat,dict)
                 for i in cat.get("issues",[]) if i.get("severity")=="critical"]
        if crits:
            for iss in crits:
                safe = iss["message"].replace("&","&amp;").replace("<","&lt;")
                story.append(Paragraph(f"• {safe}", bullet))
                if iss.get("fix"):
                    story.append(Paragraph(f"  → {iss['fix'].replace('<','&lt;')}", meta))
        else:
            story.append(Paragraph("No critical issues found! Great job.", body))

        # Warnings
        warns = [i for cat in audit.values() if isinstance(cat,dict)
                 for i in cat.get("issues",[]) if i.get("severity")=="warning"]
        if warns:
            story.append(Paragraph("Warnings", h2))
            for iss in warns[:8]:
                safe = iss["message"].replace("&","&amp;").replace("<","&lt;")
                story.append(Paragraph(f"• {safe}", bullet))

        # AI quick wins
        qws = ai.get("improvements",{}).get("quick_wins",[])
        if qws:
            story.append(PageBreak())
            story.append(Paragraph("Quick Wins — Fix Immediately", h2))
            for qw in qws:
                story.append(Paragraph(f"• {qw.get('action','')} [{qw.get('impact','')} impact]", h3))
                if qw.get("detail"):
                    story.append(Paragraph(qw["detail"].replace("<","&lt;"), body))

        # Content recommendations
        content = ai.get("content",{})
        if content.get("title_options"):
            story.append(Paragraph("Recommended Title Options", h2))
            for t_ in content.get("title_options",[]):
                safe = t_.replace("<","&lt;")
                story.append(Paragraph(f"• {safe} ({len(t_)} chars)", bullet))

        if content.get("description_options"):
            story.append(Paragraph("Recommended Meta Descriptions", h2))
            for d_ in content.get("description_options",[]):
                safe = d_.replace("<","&lt;")
                story.append(Paragraph(f"• {safe}", bullet))

        # UX tips
        ux = ai.get("ux",{})
        tips = ux.get("readability_tips",[]) + ux.get("engagement_improvements",[])
        if tips:
            story.append(Paragraph("UX & Engagement Improvements", h2))
            for tip in tips[:6]:
                story.append(Paragraph(f"• {tip.replace('<','&lt;')}", bullet))

        # Footer
        story.append(Spacer(1, 0.3*inch))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
        story.append(Paragraph(
            f"Generated by AI SEO Audit Agent · adityasharma.ai · {_date()}",
            sty("Footer", fontSize=9, textColor=GRAY)
        ))

        doc.build(story)
        buf.seek(0)
        return buf.read()

    except ImportError:
        return b"reportlab not installed. Run: pip install reportlab"
    except Exception as e:
        return f"PDF error: {e}".encode()
